apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - csidriver.yaml
  - rbac/clusterrolebindings.yaml
  - rbac/clusterroles.yaml
  - rbac/serviceaccounts.yaml
  - crds/cacerts.yaml
  - crds/clusterIssuer.yaml
  - crds/issuer.yaml