apiVersion: cacerts.csi.cert-manager.io/v1alpha1
kind: CAProviderClass
metadata:
  name: ca-provider
  namespace: spiffe-demo
spec:
  refs:
    - kind: Secret
      name: ca
      namespace: spire
      apiGroup: ""