apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-driver-cacerts

resources:
  - deployment.yaml
  - service.yaml
  - webhook.yaml
  - rbac.yaml
  - cluster-spiffe-ids.yaml
  - configmaps.yaml

images:
  - name: cacerts-webhook
    newName: fengyu225/cacerts-webhook
    newTag: v0.0.1